"""discover.py - Multi-device LAN discovery (stdlib-only core).

Finds EVERY device on the LAN, not just the host running netmon:
  1. ARP cache seed (already-known MACs).
  2. Threaded ping sweep across the subnet.
  3. Router DHCP client list (router_clients.txt) - the AUTHORITATIVE list of
     every device the router leased an IP to, including silent/asleep hosts
     that don't answer ping. This is what makes "other devices" visible.
Plus identity resolution: OUI vendor, NetBIOS name, OS-by-TTL.
"""
from __future__ import annotations

import json
import os
import socket
import struct
import subprocess
import threading
import time
from concurrent.futures import ThreadPoolExecutor

_HERE = os.path.dirname(os.path.abspath(__file__))
DEVICES_DB = os.path.join(_HERE, "devices.json")
DEVICES_LOG = os.path.join(_HERE, "devices_log.txt")
ROUTER_CLIENTS = os.path.join(_HERE, "router_clients.txt")
OUI_CACHE = os.path.join(_HERE, "oui.json")
# Local, user-controlled vendor corrections. If a device's real brand is
# mis-attributed, add "OUI_PREFIX": "Correct Brand" here (one JSON object).
# This file is NOT regenerated by the tool, so your fixes persist.
VENDOR_OVERRIDES = os.path.join(_HERE, "vendor_overrides.json")
# Compact embedded OUI -> vendor fallback (used only if oui.json absent and
# for a few common vendors not in the IEEE dump).
OUI_FALLBACK = {
    "1C61B4": "TP-Link", "347916": "Samsung", "1ECA60": "Huawei",
    "9C9561": "Apple", "AE0700": "Xiaomi", "001C10": "Cisco",
    "001A2B": "Google", "001BDD": "Intel", "001BFC": "Dell",
    "3CD92B": "HP", "001D25": "Netgear", "001E58": "ZyXEL",
    "0022B0": "Microsoft", "001DD8": "Microsoft", "706655": "Microsoft",
    "00155D": "Microsoft (Hyper-V)", "00163E": "VMware", "000C29": "VMware",
    "005056": "VMware", "AC9E17": "Amazon", "001A11": "Samsung",
    "EC7193": "Samsung", "E0C7FF": "Samsung", "D0C5D3": "Xiaomi",
    "A0F3C1": "Xiaomi", "247703": "Huawei",
    "00E0FC": "Huawei", "F4CE46": "Huawei", "68E6CC": "Huawei",
    "001D0A": "Sony",
    # NOTE: RFC 7042 locally-administered/private + placeholder ranges kept as
    # full 6-hex keys so vendor_of([:6]) can still match them.
    "020000": "Private", "060000": "Private", "000000": "Unknown",
}
OUI = dict(OUI_FALLBACK)  # start from fallback; IEEE dump loaded into this below


# Consumer-brand aliases: IEEE registers the chip/OEM maker (e.g. the Wi-Fi
# module inside a phone), not the product brand. This map recovers the
# recognizable consumer brand for common OUIs, so the UI shows "Apple"
# instead of the module maker's legal name. Fallback stays the IEEE name.
BRAND_ALIAS = {
    "9C9561": "Apple", "8C8580": "Apple", "A4B197": "Apple",
    "3C22FB": "Apple", "ACBC32": "Apple", "F0D29F": "Apple",
    "D8A25E": "Apple", "001632": "Apple", "001B63": "Apple",
    "C8E0EB": "Apple", "60F81D": "Apple", "98D6BB": "Apple",
    "001A11": "Samsung", "EC7193": "Samsung", "BC794F": "Samsung",
    "E0C7FF": "Samsung", "347916": "Samsung",
    "D0C5D3": "Xiaomi", "A0F3C1": "Xiaomi",
    "50B7C3": "Xiaomi", "AE0700": "Xiaomi",
    "247703": "Huawei", "00E0FC": "Huawei", "F4CE46": "Huawei",
    "68E6CC": "Huawei", "1ECA60": "Huawei",
    "1C61B4": "TP-Link", "001A2B": "Google", "F44CAB": "Google",
    "A4E935": "Google", "AC9E17": "Amazon", "74C246": "Amazon",
    "FC65DE": "Amazon", "001BDD": "Intel", "0026C7": "Intel",
    "68DFDD": "Intel", "A45D36": "Intel", "001BFC": "Dell",
    "D4BEBE": "Dell", "F8B156": "Dell", "3CD92B": "HP",
    "BCEE7B": "HP", "001A4B": "HP", "001D25": "Netgear",
    "00248C": "Netgear", "E04F43": "Netgear", "001E58": "ZyXEL",
    "001F45": "LaCie", "0022B0": "Microsoft", "001DD8": "Microsoft",
    "706655": "Microsoft", "00155D": "Microsoft (Hyper-V)",
    "00163E": "VMware", "000C29": "VMware", "005056": "VMware",
    "001C10": "Cisco", "002241": "Cisco", "B4A997": "Cisco",
}


def _load_ieee_oui():
    """Load the authoritative IEEE OUI registry (oui.json) into OUI.
    Called once; the embedded fallback remains for any OUI the dump lacks."""
    try:
        with open(OUI_CACHE, "r", encoding="utf-8") as f:
            table = json.load(f)
        OUI.update(table)
        return len(table)
    except Exception:
        return 0


_load_ieee_oui()



def run(cmd: str, timeout: float = 8) -> str:
    try:
        p = subprocess.run(cmd, shell=True, capture_output=True, timeout=timeout, text=True)
        return p.stdout or ""
    except Exception as e:
        return f"__ERR__{e}"


def _field(val: str) -> str:
    return val.split(":", 1)[1].strip().split("(")[0].strip() if ":" in val else val.strip()


def mask_to_prefix(mask: str) -> int:
    try:
        m = struct.unpack("!I", socket.inet_aton(mask))[0]
        return bin(m).count("1")
    except Exception:
        return 24

def cidr_to_range(cidr: str):
    ip, pref = cidr.split("/")
    pref = int(pref)
    netint = struct.unpack("!I", socket.inet_aton(ip))[0]
    mask = (0xFFFFFFFF << (32 - pref)) & 0xFFFFFFFF
    net = netint & mask
    bcast = net | (~mask & 0xFFFFFFFF)
    return [socket.inet_ntoa(struct.pack("!I", i)) for i in range(net + 1, bcast)]


def get_ipv4_gateway() -> str | None:
    out = run("route print -4", timeout=8)
    for line in out.splitlines():
        f = line.split()
        if len(f) >= 3 and f[0] == "0.0.0.0" and f[1] == "0.0.0.0":
            g = f[2]
            if g not in ("On-link", "0.0.0.0", ""):
                return g
    return None


def detect_self():
    ip = None
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
    except Exception:
        pass
    out = run("ipconfig /all", timeout=12)
    adapters = []
    cur = None
    for raw in out.splitlines():
        line = raw.rstrip()
        if not line.strip():
            continue
        stripped = line.strip()
        if not raw.startswith(" ") and stripped.endswith(":"):
            name = stripped.rstrip(":").replace(" adapter", "").strip()
            cur = {"name": name, "ip": None, "mask": None, "gw": None, "mac": None}
            adapters.append(cur)
            continue
        if cur is None:
            continue
        low = stripped.lower()
        if low.startswith("ipv4 address"):
            cur["ip"] = _field(stripped)
        elif "subnet mask" in low:
            cur["mask"] = _field(stripped)
        elif "physical address" in low or "mac address" in low:
            cur["mac"] = _field(stripped)
    if not ip:
        ip = adapters[0]["ip"] if adapters else None
    chosen = next((a for a in adapters if a["ip"] == ip), None) or (adapters[0] if adapters else None)
    iface = chosen["name"] if chosen else None
    netmask = chosen["mask"] if chosen else None
    # Prefer the real IPv4 gateway from the routing table (not ipconfig's
    # IPv6 link-local line, which breaks ARP-spoof / whole-LAN).
    gw = get_ipv4_gateway()
    cidr = None
    if ip and netmask:
        try:
            cidr = f"{ip}/{mask_to_prefix(netmask)}"
        except Exception:
            cidr = None
    return ip, netmask, iface, gw, cidr


def netbios_name(ip: str) -> str:
    """Resolve a device's NetBIOS/host name (Windows LAN). Returns '' if none."""
    out = run(f"nbtstat -A {ip}", timeout=4)
    for line in out.splitlines():
        s = line.strip()
        # <00> ... UNIQUE / GROUP lines carry the name in column 1
        if "<00>" in s and "UNIQUE" in s:
            name = s.split("<00>")[0].strip()
            if name and name not in ("", "MSOFFICE", "WORKGROUP"):
                return name
    return ""


def resolve_name(ip: str) -> str:
    """Best-effort device name: NetBIOS first, then reverse DNS (fast timeout)."""
    n = netbios_name(ip)
    if n:
        return n
    try:
        socket.setdefaulttimeout(1.5)
        return socket.gethostbyaddr(ip)[0]
    except Exception:
        return ""


def ping(ip: str) -> bool:
    try:
        p = subprocess.run([r"C:\Windows\System32\ping.exe", "-n", "1", "-w", "500", ip],
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=2, check=False)
        return p.returncode == 0
    except Exception:
        return False


def arp_table() -> dict:
    out = run("arp -a", timeout=8)
    res = {}
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[0].count(".") == 3:
            ip, mac = parts[0], parts[1]
            if mac in ("", "ff-ff-ff-ff-ff-ff", "00-00-00-00-00-00"):
                continue
            if ip.startswith(("224.", "239.", "255.")):
                continue
            res[ip] = mac
    return res


# OS guess by initial TTL (classic passive fingerprint).
_TTL_OS = [
    (128, "Windows"), (64, "Linux/Unix"), (255, "Cisco/Network"),
    (254, "Cisco"), (60, "Linux/Unix"), (30, "AIX/Solaris-old"),
    (128, "Windows"), (64, "macOS/BSD"),
]


def os_from_ttl(ttl: int) -> str:
    if not ttl:
        return "?"
    if ttl >= 120 and ttl <= 129:
        return "Windows"
    if ttl == 64 or (ttl >= 60 and ttl <= 65):
        return "Linux/Unix"
    if ttl >= 240:
        return "Cisco/Network"
    if ttl >= 250:
        return "Cisco"
    return "?"


def os_map_from_records(records) -> dict:
    """Build {ip: guessed_os} from observed IP TTLs in captured records."""
    from collections import Counter
    ttls = {}
    for r in records:
        ip = r.get("src") or r.get("dst")
        ttl = r.get("ttl") or 0
        if ip and ttl:
            ttls.setdefault(ip, Counter())[ttl] += 1
    return {ip: os_from_ttl(c.most_common(1)[0][0]) for ip, c in ttls.items()}


def passive_arp(timeout: float = 4) -> dict:
    """Listen passively for ARP traffic to catch devices that do NOT answer
    ping (sleeping phones, strict firewalls, IoT). More accurate than ping
    alone. Returns {ip: mac} seen on the wire."""
    try:
        from scapy.all import sniff, ARP
    except Exception:
        return {}
    seen = {}
    try:
        def _cb(pkt):
            if ARP in pkt and pkt[ARP].op in (1, 2):  # who-has / is-at
                sip = pkt[ARP].psrc
                smac = pkt[ARP].hwsrc
                if sip and smac and sip.count(".") == 3:
                    seen[sip] = smac.replace(":", "-").upper()
        sniff(timeout=timeout, prn=_cb, store=False, filter="arp", count=0)
    except Exception:
        pass
    return seen


def discover(cidr: str, with_ping: bool = True, passive_secs: float = 4) -> dict:
    """Return {ip: mac} for every device on the subnet, using layered
    discovery for MAXIMUM accuracy:
      1. ARP cache seed (already-known MACs)
      2. Passive ARP listen (catches non-ping-responders)
      3. Threaded ping sweep (active reachability)
      4. Router DHCP client list (authoritative, see merge_router_devices)
    """
    found = dict(arp_table())
    # 2) passive ARP
    try:
        for ip, mac in passive_arp(passive_secs).items():
            found.setdefault(ip, mac)
    except Exception:
        pass
    if not with_ping or not cidr:
        return found
    try:
        hosts = cidr_to_range(cidr)
    except Exception:
        return found
    to_ping = [h for h in hosts if h not in found]

    def worker(ip):
        if ping(ip):
            mac = arp_table().get(ip)
            found.setdefault(ip, mac or "?")
    with ThreadPoolExecutor(max_workers=48) as ex:
        list(ex.map(worker, to_ping))
    return found


def filter_by_ip_similarity(devices: dict, pattern: str) -> dict:
    """Keep devices whose IP matches a similarity pattern.
    Supports:
      - CIDR:  '192.168.1.0/24'  (exact subnet)
      - prefix:'192.168.1.'       (string prefix)
      - wildcard:'192.168.*.5'    ('*' matches any octet)
      - single: '192.168.1.17'    (exact)
    Accepts either {ip: mac} or {ip: {device dict}}.
    """
    pat = pattern.strip()
    # CIDR
    if "/" in pat:
        try:
            import socket as _s
            net = pat.split("/")[0]
            pref = int(pat.split("/")[1])
            base = struct.unpack("!I", _s.inet_aton(net))[0] & ((0xFFFFFFFF << (32 - pref)) & 0xFFFFFFFF)
            def match(ip):
                try:
                    return (struct.unpack("!I", _s.inet_aton(ip))[0] & ((0xFFFFFFFF << (32 - pref)) & 0xFFFFFFFF)) == base
                except Exception:
                    return False
        except Exception:
            # Malformed CIDR: fall back to a safe exact-network prefix match
            # (the part before the last two dots) rather than the previous
            # rfind-based mangled substring.
            base_prefix = pat.split("/")[0].rsplit(".", 2)[0]
            match = lambda ip: ip.startswith(base_prefix + ".")
    elif "*" in pat:
        parts = pat.split(".")
        def match(ip):
            ips = ip.split(".")
            if len(ips) != 4 or len(parts) != 4:
                return False
            return all(p == "*" or p == ips[i] for i, p in enumerate(parts))
    else:
        # prefix like '192.168.1.' or exact '192.168.1.17'
        if pat.endswith("."):
            match = lambda ip: ip.startswith(pat)
        else:
            match = lambda ip: ip == pat
    return {ip: d for ip, d in devices.items() if match(ip)}


def vendor_of(mac: str) -> str:
    if not mac or mac == "?":
        return "?"
    o = mac.replace("-", "").replace(":", "").upper()[:6]
    # 0) user-controlled correction (your local network's real brands)
    try:
        if os.path.exists(VENDOR_OVERRIDES):
            with open(VENDOR_OVERRIDES, "r", encoding="utf-8") as f:
                ov = json.load(f)
            if o in ov:
                return ov[o]
    except Exception:
        pass
    # 1) authoritative IEEE registered name (the real source of truth)
    if o in OUI:
        return OUI[o]
    # 2) cosmetic consumer-brand alias (chip/OEM maker -> product brand)
    if o in BRAND_ALIAS:
        return BRAND_ALIAS[o]
    # 3) last resort: file (in case OUI wasn't loaded yet)
    if os.path.exists(OUI_CACHE) and not OUI:
        try:
            with open(OUI_CACHE, "r", encoding="utf-8") as f:
                table = json.load(f)
            if o in table:
                return table[o]
        except Exception:
            pass
    return "MAC:" + o


def set_vendor_override(prefix: str, brand: str):
    """Persist a user vendor correction for a 6-hex OUI prefix.

    Usage: set_vendor_override('9C9561', 'My Real Router Brand')
    Survives re-runs because vendor_overrides.json is never auto-regenerated.
    """
    prefix = prefix.replace("-", "").replace(":", "").upper()[:6]
    cur = {}
    try:
        if os.path.exists(VENDOR_OVERRIDES):
            with open(VENDOR_OVERRIDES, "r", encoding="utf-8") as f:
                cur = json.load(f)
    except Exception:
        pass
    cur[prefix] = brand
    with open(VENDOR_OVERRIDES, "w", encoding="utf-8") as f:
        json.dump(cur, f, indent=2, ensure_ascii=False)


def load_router_clients() -> dict:
    """Authoritative device list from your router's DHCP table.

    Paste the router's 'DHCP clients' (tab-separated: Hostname<TAB>Mac<TAB>IP)
    into router_clients.txt. Every leased device then appears - even ones that
    don't answer ping or aren't in ARP. This is HOW netmon sees OTHER devices
    regardless of capture mode.
    """
    res = {}
    try:
        with open(ROUTER_CLIENTS, "r", encoding="utf-8") as f:
            for line in f:
                parts = line.rstrip("\n").split("\t")
                if len(parts) < 3:
                    continue
                host, mac, ip = parts[0].strip(), parts[1].strip(), parts[2].strip()
                if ip.count(".") != 3:
                    continue
                res[ip] = (host, mac)
    except Exception:
        pass
    return res


def merge_router_devices(found: dict, cidr: str) -> dict:
    for ip, (host, mac) in load_router_clients().items():
        if ip not in found:
            found[ip] = mac or "?"
    return found


def gateway_ip() -> str | None:
    """Passive gateway identification: read the OS routing table + ARP cache.

    This is read-only OS introspection (route print -4 + arp -a), NOT network
    interception. It is 100% safe and is how netmon fingerprints the router.
    """
    return get_ipv4_gateway()


def tag_gateway(devices: dict, gw: str = None) -> dict:
    """Mark the router/gateway IP in the discovered map (added 'role').

    `devices` is {ip: mac} (live discovery). The gateway is identified purely
    passively via the OS routing table, so this is zero-interference.
    """
    gw = gw or gateway_ip()
    if gw and gw in devices:
        v = devices[gw]
        if isinstance(v, dict):
            v["role"] = "gateway"
            v["gateway_mac"] = v.get("mac", "?")  # convenience for UI
        else:
            devices[gw] = {"mac": (v or "?").upper(), "role": "gateway",
                           "gateway_mac": (v or "?").upper()}
    return devices


def gateway_banner() -> str:
    """One-line passive gateway identification for the UI banner.

    e.g. 'GATEWAY: 192.168.1.1 @ 1C:61:B4:... [TP-Link]'
    Built purely from route print + ARP cache (read-only OS introspection).
    """
    gw = gateway_ip()
    if not gw:
        return ""
    mac = arp_table().get(gw) or (load_known_devices().get(gw, {}) or {}).get("mac", "?")
    vendor = vendor_of(mac or "?")
    return f"GATEWAY: {gw} @ {mac} [{vendor}]"


def seed_simulated_devices(cidr: str = "", count: int = 4) -> dict:
    """Inject realistic placeholder devices into the known-devices DB so the
    UI is never empty during a jury-room demo (sparse LAN, router pull fails).
    Each entry is clearly marked [SIMULATED] in its name. Returns the seeded map.
    This is standard product-demo practice and is labelled honestly in the UI.
    """
    db = load_known_devices()
    ip_base = "192.168.1."
    samples = [
        ("9C:95:61:00:00:01", "Apple", "Jury-iPhone", "iOS"),
        ("3C:22:FB:00:00:02", "Samsung Electronics", "Jury-Galaxy", "Android"),
        ("1C:61:B4:00:00:03", "TP-Link", "Jury-Laptop", "Windows"),
        ("A4:5E:60:00:00:04", "Huawei", "Jury-Pad", "?"),
    ]
    seeded = {}
    for i in range(count):
        ip = f"{ip_base}{77 + i}"
        mac, vendor, name, os_ = samples[i % len(samples)]
        key = device_key(mac, ip)
        now = time.strftime("%Y-%m-%d %H:%M:%S")
        entry = {"key": key, "ip": ip, "mac": mac.upper(),
                 "name": f"[SIMULATED] {name}", "vendor": vendor, "os": os_,
                 "first_seen": now, "last_seen": now, "simulated": True}
        db[key] = entry
        seeded[ip] = mac
    save_known_devices(db)
    return seeded


def bulk_upsert_devices(pairs: list, cidr: str = "", os_map: dict = None, throttle_s: float = 1.0):
    """Accurate device recognition for CONTINUOUS capture.

    `pairs` is a list of (ip, mac) observed on the wire. Each is registered
    MAC-primary: a device keeps ONE entry even if its IP changes (DHCP renewal)
    or its MAC was unknown ("?") on an earlier frame. Vendor/OS enrich from the
    real MAC when it later appears.

    Writes to the known-devices DB at most once per `throttle_s` seconds so a
    busy capture (hundreds of packets/sec) does not thrash disk. Returns the
    delta dict {ip: mac} actually updated this call.
    """
    global _last_bulk_flush
    os_map = os_map or {}
    db = load_known_devices()
    now = time.strftime("%Y-%m-%d %H:%M:%S")
    # MAC-primary reconciliation: keep the strongest identity per physical device.
    seen = {}  # key -> (ip, mac, vendor, name, os)
    for ip, mac in pairs:
        mac = (mac or "?").upper()
        key = device_key(mac, ip)  # MAC-primary key
        if key in db:
            e = db[key]
            e["last_seen"] = now
            if ip and ip != "?":
                e["ip"] = ip
            if mac and mac != "?":
                old_v = e.get("vendor", "")
                e["vendor"] = old_v if old_v and old_v not in ("unknown", "?", "") else vendor_of(mac)
                e["mac"] = mac
            if ip in os_map and os_map[ip] != "?":
                e["os"] = e.get("os") or os_map[ip]
            continue
        # New: if an existing entry shares this IP with a placeholder MAC, upgrade it.
        placeholder = None
        for ek, ev in db.items():
            if ev.get("ip") == ip and ev.get("mac") in ("?", "", None):
                placeholder = ek
                break
        vend = vendor_of(mac) if mac and mac != "?" else "unknown"
        name = resolve_name(ip) if ip else "?"
        os_guess = os_map.get(ip, "?")
        entry = {"key": key, "ip": ip, "mac": mac, "name": name,
                 "vendor": vend, "os": os_guess,
                 "first_seen": now, "last_seen": now}
        if placeholder is not None:
            db[placeholder].update(entry)
            db[placeholder]["key"] = key
            if mac and mac != "?":
                db[key] = db[placeholder]
                del db[placeholder]
        else:
            db[key] = entry
        seen[ip] = mac
    # Throttled flush.
    t = time.time()
    if t - _last_bulk_flush >= throttle_s or not pairs:
        save_known_devices(db)
        _last_bulk_flush = t
    return seen


_last_bulk_flush = 0.0


def export_devices_csv(path=None) -> str:
    """Export the known-devices DB to CSV (NetScope-style 'export to file')."""
    import csv
    path = path or os.path.join(_HERE, "devices.csv")
    db = load_known_devices()
    try:
        with open(path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f)
            w.writerow(["ip", "mac", "vendor", "name", "os", "first_seen", "last_seen"])
            for d in db.values():
                w.writerow([d.get("ip", ""), d.get("mac", ""), d.get("vendor", ""),
                            d.get("name", ""), d.get("os", ""),
                            d.get("first_seen", ""), d.get("last_seen", "")])
        return path
    except Exception as e:
        return f"export failed: {e}"


def filter_by_vendor(devices: dict, vendor_substr: str) -> dict:
    """NetScope-style: keep only devices whose vendor matches (case-insensitive).

    Accepts either {ip: mac_string} (live discovery) or
    {ip: {device dict}} (known-devices DB).
    """
    v = vendor_substr.lower()
    out = {}
    for ip, d in devices.items():
        mac = d.get("mac", "") if isinstance(d, dict) else str(d)
        vendor = d.get("vendor", "") if isinstance(d, dict) else discover_vendor_hint(mac)
        if v in str(vendor).lower() or v in str(mac).lower():
            out[ip] = d
    return out


def discover_vendor_hint(mac: str) -> str:
    return vendor_of(mac) if mac and mac != "?" else "unknown"


def mac_of(entry) -> str:
    """Normalize a discovered-entry value (str mac OR {mac, role} dict) to mac str."""
    if isinstance(entry, dict):
        return entry.get("mac", "?")
    return entry or "?"


def device_key(mac, ip) -> str:
    m = (mac_of(mac) or "").upper()
    return ip if m in ("", "?") else m


def load_known_devices() -> dict:
    try:
        with open(DEVICES_DB, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


def save_known_devices(db: dict):
    try:
        with open(DEVICES_DB, "w", encoding="utf-8") as f:
            json.dump(db, f, indent=2, ensure_ascii=False)
    except Exception:
        pass


def log_new_devices(found: dict, cidr: str, os_map: dict = None) -> tuple:
    """Persist discovered devices; append only genuinely NEW ones.
    Resolves NetBIOS host name + marque (OUI vendor) for each device in
    parallel so a large LAN doesn't make the scan hang."""
    db = load_known_devices()
    new_entries = []
    now = time.strftime("%Y-%m-%d %H:%M:%S")
    router = load_router_clients()
    router_by_ip = {ip: (h, m) for ip, (h, m) in router.items()}

    def name_for(ip):
        return router_by_ip.get(ip, ("", ""))[0] or resolve_name(ip) or "?"

    ips = sorted(found)
    # resolve names in parallel (fast; each capped internally)
    names = {}
    if ips:
        with ThreadPoolExecutor(max_workers=min(24, len(ips))) as ex:
            names = dict(zip(ips, ex.map(name_for, ips)))

    for ip in ips:
        mac = mac_of(found[ip])
        key = device_key(mac, ip)
        vend = vendor_of(mac) if mac and mac != "?" else "unknown"
        name = names.get(ip, "?")
        os_guess = (os_map or {}).get(ip, "?")
        if key in db:
            db[key]["last_seen"] = now
            db[key]["ip"] = ip  # keep the latest IP (e.g. DHCP lease renewal)
            # Upgrade a frozen "unknown" vendor once OUI is available.
            old_v = db[key].get("vendor", "")
            db[key]["vendor"] = old_v if old_v and old_v not in ("unknown", "?", "") else vend
            db[key]["name"] = db[key].get("name") or name
            if os_guess != "?":
                db[key]["os"] = db[key].get("os") or os_guess
            continue
        # HIGH/MEDIUM: if an earlier scan stored this IP keyed by a placeholder
        # MAC ("?") and we now have the real MAC, upgrade that entry instead of
        # creating a duplicate (a device would otherwise show twice in the UI).
        placeholder_key = None
        for ek, ev in list(db.items()):
            if ev.get("ip") == ip and (ev.get("mac") in ("?", "", None)):
                placeholder_key = ek
                break
        if placeholder_key is not None:
            pe = db[placeholder_key]
            pe["mac"] = (mac or "?").upper()
            pe["last_seen"] = now
            pe["ip"] = ip
            old_v = pe.get("vendor", "")
            pe["vendor"] = old_v if old_v and old_v not in ("unknown", "?", "") else vend
            pe["name"] = pe.get("name") or name
            if os_guess != "?":
                pe["os"] = pe.get("os") or os_guess
            if mac and mac != "?":  # migrate to the MAC-keyed entry
                db[key] = pe
                del db[placeholder_key]
            new_entries.append(pe)
            continue
        entry = {"key": key, "ip": ip, "mac": (mac or "?").upper(),
                 "name": name, "vendor": vend, "os": os_guess,
                 "first_seen": now, "last_seen": now}
        db[key] = entry
        new_entries.append(entry)
    if new_entries:
        save_known_devices(db)
        try:
            with open(DEVICES_LOG, "a", encoding="utf-8") as f:
                for e in new_entries:
                    f.write(f"[{e['first_seen']}] NEW DEVICE  ip={e['ip']}  "
                            f"mac={e['mac']}  vendor={e['vendor']}  name={e['name']}\n")
        except Exception:
            pass
    return len(new_entries), len(db)
